stages:
  - tests

python2.7:
  type: test
  stage: tests
  image: python:2.7
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage

python3.5:
  type: test
  stage: tests
  image: python:3.5
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage

python3.6:
  type: test
  stage: tests
  image: python:3.6
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage
