stages:
  - tests
  - release

python2.7:
  stage: tests
  image: python:2.7
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage

python3.5:
  stage: tests
  image: python:3.5
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage

python3.6:
  stage: tests
  image: python:3.6
  before_script:
    - pip install -r development_requirements.txt
  script:
   - nosetests --cover-package=pyEchosign --with-coverage

release:
  stage: release
  image: python:3.6
  before_script:
    - pip install twine
  script:
    - python setup.py bdist_wheel --universal
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags